import {
  GraduationCap, Presentation, Search, Compass, Route, BookOpen, Code2, Rocket, Award,
  Briefcase, Send, Mic, Trophy, TrendingUp, LayoutDashboard, Map, ClipboardList, Terminal,
  FileText, BarChart3, Bookmark, Gauge, Calendar, Gamepad2, ShieldCheck, Flame, PlayCircle,
  UploadCloud, Video, CheckSquare, Users, MessageCircle, Wallet, HandHeart, Building2,
  Clock, Sparkles, Filter, MailCheck, Bot, Bell, Lock, Cloud, Zap, Eye, Target, Lightbulb,
  Globe2, Star, Quote, CircleUser, Heart, Layers, PenLine, Network, Puzzle, Brain, GitBranch,
} from 'lucide-react'

const ICONS = {
  graduation: GraduationCap,
  presentation: Presentation,
  search: Search,
  compass: Compass,
  route: Route,
  book: BookOpen,
  code: Code2,
  rocket: Rocket,
  award: Award,
  briefcase: Briefcase,
  send: Send,
  mic: Mic,
  trophy: Trophy,
  trend: TrendingUp,
  dashboard: LayoutDashboard,
  map: Map,
  clipboard: ClipboardList,
  terminal: Terminal,
  file: FileText,
  chart: BarChart3,
  bookmark: Bookmark,
  gauge: Gauge,
  calendar: Calendar,
  gamepad: Gamepad2,
  shield: ShieldCheck,
  flame: Flame,
  'play-circle': PlayCircle,
  upload: UploadCloud,
  video: Video,
  'check-square': CheckSquare,
  users: Users,
  message: MessageCircle,
  wallet: Wallet,
  hand: HandHeart,
  building: Building2,
  clock: Clock,
  sparkles: Sparkles,
  filter: Filter,
  'mail-check': MailCheck,
  bot: Bot,
  bell: Bell,
  lock: Lock,
  cloud: Cloud,
  zap: Zap,
  eye: Eye,
  target: Target,
  'bar-chart': BarChart3,
  note: PenLine,
  student: GraduationCap,
  trainer: Presentation,
  recruiter: Briefcase,
  ai: Bot,
  bulb: Lightbulb,
  globe: Globe2,
  star: Star,
  quote: Quote,
  user: CircleUser,
  heart: Heart,
  layers: Layers,
  network: Network,
  puzzle: Puzzle,
  brain: Brain,
  git: GitBranch,
}

export function Icon({ name, size = 20, strokeWidth = 1.8, className = '' }) {
  const Cmp = ICONS[name] || Sparkles
  return <Cmp size={size} strokeWidth={strokeWidth} className={className} aria-hidden="true" />
}
